name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
    paths:
    - 'gh-deployment-workflow/index.html'
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  preload:
    runs-on: ubuntu-latest
    steps:
    - name: Preload upload-artifact@v3
      uses: actions/upload-artifact@v3
      with:
        name: preload
        path: README.md # any small file that exists

  deploy:
    needs: preload # wait for preload job to finish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: gh-deployment-workflow

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      id: deployment
