name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
    paths:
    - 'gh-deployment-workflow/index.html'
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: gh-deployment-workflow # ✅ Make sure this matches actual folder

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
